In [25]:
'''
    转换探空气球采集的数据的格式
    北京时 = 世界时 + 8
    探空崎岖采集的是世界时的00时和12时
'''
import pandas as pd 
import read_filepath_module

Level_1_path = r'I:\Data\Personal Data\graduation project\SACOL\Balloon\2009'
Target_str = 'sounding_data'
Output_paths = read_filepath_module.read_filepath(Level_1_path,Target_str)
# Output_paths = Output_paths[4]
print(Output_paths)

['I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200901\\sounding_data_as_MWR_format_200901.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200902\\sounding_data_as_MWR_format_200902.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200903\\sounding_data_as_MWR_format_200903.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200904\\sounding_data_as_MWR_format_200904.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200905\\sounding_data_as_MWR_format_200905.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200906\\sounding_data_as_MWR_format_200906.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200907\\sounding_data_as_MWR_format_200907.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200908\\sounding_data_as_MWR_format_200908.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200909\\sounding_data_as_MWR_format_200909.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200910\\sounding_data_as_MWR_format_200910.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200911\\sounding_data_as_MWR_format_200911.txt', 'I:\\Data\\Personal Data\\graduation project\\SACOL\\Balloon\\2009\\200912\\sounding_data_as_MWR_format_200912.txt']

In [26]:
def modify_index(filepath):
    data = pd.read_csv(Output_path,sep='  ',encoding = "UTF-8")
    i = 0
    while i<data.shape[0]: 
        print(i)
        str11 = str(data.loc[i:i,'Time'].values)
        print('str11',str11)
        data.loc[i:i,'Time'] = str11[1:9] + '_BjT' + str11[9:11] + '00'
        print("data.loc[i:i,'Time']",data.loc[i:i,'Time'],'\n')
        i = i + 1
    return(data)

In [27]:
for Output_path in Output_paths:
    Output = modify_index(Output_path)
    filename = Output_path[0:60] + 'UPAR' + Output_path[95:101] + '.csv'
    # print(filename)
    Output.to_csv(filename,index=0)

3_BjT0000
Name: Time, dtype: object

25
str11 [2009091312]
data.loc[i:i,'Time'] 25    20090913_BjT1200
Name: Time, dtype: object

26
str11 [2009091400]
data.loc[i:i,'Time'] 26    20090914_BjT0000
Name: Time, dtype: object

27
str11 [2009091412]
data.loc[i:i,'Time'] 27    20090914_BjT1200
Name: Time, dtype: object

28
str11 [2009091500]
data.loc[i:i,'Time'] 28    20090915_BjT0000
Name: Time, dtype: object

29
str11 [2009091512]
data.loc[i:i,'Time'] 29    20090915_BjT1200
Name: Time, dtype: object

30
str11 [2009091600]
data.loc[i:i,'Time'] 30    20090916_BjT0000
Name: Time, dtype: object

31
str11 [2009091612]
data.loc[i:i,'Time'] 31    20090916_BjT1200
Name: Time, dtype: object

32
str11 [2009091700]
data.loc[i:i,'Time'] 32    20090917_BjT0000
Name: Time, dtype: object

33
str11 [2009091712]
data.loc[i:i,'Time'] 33    20090917_BjT1200
Name: Time, dtype: object

34
str11 [2009091800]
data.loc[i:i,'Time'] 34    20090918_BjT0000
Name: Time, dtype: object

35
str11 [2009091812]
data.loc[i:i,'Time'] 35    20090918_BjT1200
Name: Time, dtype: object

36
str11 [2009091900]
data.loc[i:i,'Time'] 36    20090919_BjT0000
Name: Time, dtype: object

37
str11 [2009091912]
data.loc[i:i,'Time'] 37    20090919_BjT1200
Name: Time, dtype: object

38
str11 [2009092000]
data.loc[i:i,'Time'] 38    20090920_BjT0000
Name: Time, dtype: object

39
str11 [2009092012]
data.loc[i:i,'Time'] 39    20090920_BjT1200
Name: Time, dtype: object

40
str11 [2009092100]
data.loc[i:i,'Time'] 40    20090921_BjT0000
Name: Time, dtype: object

41
str11 [2009092112]
data.loc[i:i,'Time'] 41    20090921_BjT1200
Name: Time, dtype: object

42
str11 [2009092200]
data.loc[i:i,'Time'] 42    20090922_BjT0000
Name: Time, dtype: object

43
str11 [2009092212]
data.loc[i:i,'Time'] 43    20090922_BjT1200
Name: Time, dtype: object

44
str11 [2009092300]
data.loc[i:i,'Time'] 44    20090923_BjT0000
Name: Time, dtype: object

45
str11 [2009092312]
data.loc[i:i,'Time'] 45    20090923_BjT1200
Name: Time, dtype: object

46
str11 [2009092400]
data.loc[i:i,'Time'] 46    20090924_BjT0000
Name: Time, dtype: object

47
str11 [2009092412]
data.loc[i:i,'Time'] 47    20090924_BjT1200
Name: Time, dtype: object

48
str11 [2009092500]
data.loc[i:i,'Time'] 48    20090925_BjT0000
Name: Time, dtype: object

49
str11 [2009092600]
data.loc[i:i,'Time'] 49    20090926_BjT0000
Name: Time, dtype: object

50
str11 [2009092612]
data.loc[i:i,'Time'] 50    20090926_BjT1200
Name: Time, dtype: object

51
str11 [2009092700]
data.loc[i:i,'Time'] 51    20090927_BjT0000
Name: Time, dtype: object

52
str11 [2009092712]
data.loc[i:i,'Time'] 52    20090927_BjT1200
Name: Time, dtype: object

53
str11 [2009092800]
data.loc[i:i,'Time'] 53    20090928_BjT0000
Name: Time, dtype: object

54
str11 [2009092900]
data.loc[i:i,'Time'] 54    20090929_BjT0000
Name: Time, dtype: object

55
str11 [2009092912]
data.loc[i:i,'Time'] 55    20090929_BjT1200
Name: Time, dtype: object

56
str11 [2009093000]
data.loc[i:i,'Time'] 56    20090930_BjT0000
Name: Time, dtype: object

57
str11 [2009093012]
data.loc[i:i,'Time'] 57    20090930_BjT1200
Name: Time, dtype: object

0
str11 [2009100100]
data.loc[i:i,'Time'] 0    20091001_BjT0000
Name: Time, dtype: object

1
str11 [2009100112]
data.loc[i:i,'Time'] 1    20091001_BjT1200
Name: Time, dtype: object

2
str11 [2009100200]
data.loc[i:i,'Time'] 2    20091002_BjT0000
Name: Time, dtype: object

3
str11 [2009100212]
data.loc[i:i,'Time'] 3    20091002_BjT1200
Name: Time, dtype: object

4
str11 [2009100300]
data.loc[i:i,'Time'] 4    20091003_BjT0000
Name: Time, dtype: object

5
str11 [2009100312]
data.loc[i:i,'Time'] 5    20091003_BjT1200
Name: Time, dtype: object

6
str11 [2009100400]
data.loc[i:i,'Time'] 6    20091004_BjT0000
Name: Time, dtype: object

7
str11 [2009100412]
data.loc[i:i,'Time'] 7    20091004_BjT1200
Name: Time, dtype: object

8
str11 [2009100500]
data.loc[i:i,'Time'] 8    20091005_BjT0000
Name: Time, dtype: object

9
str11 [2009100512]
data.loc[i:i,'Time'] 9    20091005_BjT1200
Name: Time, dtype: object

10
str11 [2009100600]
data.loc[i:i,'Time'] 10    20091006_BjT0000
Name: Time, dtype: object

11
str11 [2009100612]
data.loc[i:i,'Time'] 11    20091006_BjT1200
Name: Time, dtype: object

12
str11 [2009100700]
data.loc[i:i,'Time'] 12    20091007_BjT0000
Name: Time, dtype: object

13
str11 [2009100712]
data.loc[i:i,'Time'] 13    20091007_BjT1200
Name: Time, dtype: object

14
str11 [2009100800]
data.loc[i:i,'Time'] 14    20091008_BjT0000
Name: Time, dtype: object

15
str11 [2009100812]
data.loc[i:i,'Time'] 15    20091008_BjT1200
Name: Time, dtype: object

16
str11 [2009100900]
data.loc[i:i,'Time'] 16    20091009_BjT0000
Name: Time, dtype: object

17
str11 [2009100912]
data.loc[i:i,'Time'] 17    20091009_BjT1200
Name: Time, dtype: object

18
str11 [2009101000]
data.loc[i:i,'Time'] 18    20091010_BjT0000
Name: Time, dtype: object

19
str11 [2009101012]
data.loc[i:i,'Time'] 19    20091010_BjT1200
Name: Time, dtype: object

20
str11 [2009101100]
data.loc[i:i,'Time'] 20    20091011_BjT0000
Name: Time, dtype: object

21
str11 [2009101112]
data.loc[i:i,'Time'] 21    20091011_BjT1200
Name: Time, dtype: object

22
str11 [2009101200]
data.loc[i:i,'Time'] 22    20091012_BjT0000
Name: Time, dtype: object

23
str11 [2009101212]
data.loc[i:i,'Time'] 23    20091012_BjT1200
Name: Time, dtype: object

24
str11 [2009101300]
data.loc[i:i,'Time'] 24    20091013_BjT0000
Name: Time, dtype: object

25
str11 [2009101312]
data.loc[i:i,'Time'] 25    20091013_BjT1200
Name: Time, dtype: object

26
str11 [2009101400]
data.loc[i:i,'Time'] 26    20091014_BjT0000
Name: Time, dtype: object

27
str11 [2009101412]
data.loc[i:i,'Time'] 27    20091014_BjT1200
Name: Time, dtype: object

28
str11 [2009101500]
data.loc[i:i,'Time'] 28    20091015_BjT0000
Name: Time, dtype: object

29
str11 [2009101512]
data.loc[i:i,'Time'] 29    20091015_BjT1200
Name: Time, dtype: object

30
str11 [2009101600]
data.loc[i:i,'Time'] 30    20091016_BjT0000
Name: Time, dtype: object

31
str11 [2009101612]
data.loc[i:i,'Time'] 31    20091016_BjT1200
Name: Time, dtype: object

32
str11 [2009101700]
data.loc[i:i,'Time'] 32    20091017_BjT0000
Name: Time, dtype: object

33
str11 [2009101712]
data.loc[i:i,'Time'] 33    20091017_BjT1200
Name: Time, dtype: object

34
str11 [2009101800]
data.loc[i:i,'Time'] 34    20091018_BjT0000
Name: Time, dtype: object

35
str11 [2009101812]
data.loc[i:i,'Time'] 35    20091018_BjT1200
Name: Time, dtype: object

36
str11 [2009101900]
data.loc[i:i,'Time'] 36    20091019_BjT0000
Name: Time, dtype: object

37
str11 [2009101912]
data.loc[i:i,'Time'] 37    20091019_BjT1200
Name: Time, dtype: object

38
str11 [2009102000]
data.loc[i:i,'Time'] 38    20091020_BjT0000
Name: Time, dtype: object

39
str11 [2009102012]
data.loc[i:i,'Time'] 39    20091020_BjT1200
Name: Time, dtype: object

40
str11 [2009102100]
data.loc[i:i,'Time'] 40    20091021_BjT0000
Name: Time, dtype: object

41
str11 [2009102112]
data.loc[i:i,'Time'] 41    20091021_BjT1200
Name: Time, dtype: object

42
str11 [2009102200]
data.loc[i:i,'Time'] 42    20091022_BjT0000
Name: Time, dtype: object

43
str11 [2009102212]
data.loc[i:i,'Time'] 43    20091022_BjT1200
Name: Time, dtype: object

44
str11 [2009102300]
data.loc[i:i,'Time'] 44    20091023_BjT0000
Name: Time, dtype: object

45
str11 [2009102312]
data.loc[i:i,'Time'] 45    20091023_BjT1200
Name: Time, dtype: object

46
str11 [2009102400]
data.loc[i:i,'Time'] 46    20091024_BjT0000
Name: Time, dtype: object

47
str11 [2009102412]
data.loc[i:i,'Time'] 47    20091024_BjT1200
Name: Time, dtype: object

48
str11 [2009102500]
data.loc[i:i,'Time'] 48    20091025_BjT0000
Name: Time, dtype: object

49
str11 [2009102512]
data.loc[i:i,'Time'] 49    20091025_BjT1200
Name: Time, dtype: object

50
str11 [2009102600]
data.loc[i:i,'Time'] 50    20091026_BjT0000
Name: Time, dtype: object

51
str11 [2009102612]
data.loc[i:i,'Time'] 51    20091026_BjT1200
Name: Time, dtype: object

52
str11 [2009102700]
data.loc[i:i,'Time'] 52    20091027_BjT0000
Name: Time, dtype: object

53
str11 [2009102712]
data.loc[i:i,'Time'] 53    20091027_BjT1200
Name: Time, dtype: object

54
str11 [2009102812]
data.loc[i:i,'Time'] 54    20091028_BjT1200
Name: Time, dtype: object

55
str11 [2009102900]
data.loc[i:i,'Time'] 55    20091029_BjT0000
Name: Time, dtype: object

56
str11 [2009102912]
data.loc[i:i,'Time'] 56    20091029_BjT1200
Name: Time, dtype: object

57
str11 [2009103000]
data.loc[i:i,'Time'] 57    20091030_BjT0000
Name: Time, dtype: object

58
str11 [2009103012]
data.loc[i:i,'Time'] 58    20091030_BjT1200
Name: Time, dtype: object

59
str11 [2009103100]
data.loc[i:i,'Time'] 59    20091031_BjT0000
Name: Time, dtype: object

60
str11 [2009103112]
data.loc[i:i,'Time'] 60    20091031_BjT1200
Name: Time, dtype: object

0
str11 [2009110100]
data.loc[i:i,'Time'] 0    20091101_BjT0000
Name: Time, dtype: object

1
str11 [2009110112]
data.loc[i:i,'Time'] 1    20091101_BjT1200
Name: Time, dtype: object

2
str11 [2009110200]
data.loc[i:i,'Time'] 2    20091102_BjT0000
Name: Time, dtype: object

3
str11 [2009110212]
data.loc[i:i,'Time'] 3    20091102_BjT1200
Name: Time, dtype: object

4
str11 [2009110300]
data.loc[i:i,'Time'] 4    20091103_BjT0000
Name: Time, dtype: object

5
str11 [2009110312]
data.loc[i:i,'Time'] 5    20091103_BjT1200
Name: Time, dtype: object

6
str11 [2009110400]
data.loc[i:i,'Time'] 6    20091104_BjT0000
Name: Time, dtype: object

7
str11 [2009110412]
data.loc[i:i,'Time'] 7    20091104_BjT1200
Name: Time, dtype: object

8
str11 [2009110500]
data.loc[i:i,'Time'] 8    20091105_BjT0000
Name: Time, dtype: object

9
str11 [2009110512]
data.loc[i:i,'Time'] 9    20091105_BjT1200
Name: Time, dtype: object

10
str11 [2009110600]
data.loc[i:i,'Time'] 10    20091106_BjT0000
Name: Time, dtype: object

11
str11 [2009110612]
data.loc[i:i,'Time'] 11    20091106_BjT1200
Name: Time, dtype: object

12
str11 [2009110700]
data.loc[i:i,'Time'] 12    20091107_BjT0000
Name: Time, dtype: object

13
str11 [2009110712]
data.loc[i:i,'Time'] 13    20091107_BjT1200
Name: Time, dtype: object

14
str11 [2009110800]
data.loc[i:i,'Time'] 14    20091108_BjT0000
Name: Time, dtype: object

15
str11 [2009110812]
data.loc[i:i,'Time'] 15    20091108_BjT1200
Name: Time, dtype: object

16
str11 [2009110900]
data.loc[i:i,'Time'] 16    20091109_BjT0000
Name: Time, dtype: object

17
str11 [2009110912]
data.loc[i:i,'Time'] 17    20091109_BjT1200
Name: Time, dtype: object

18
str11 [2009111000]
data.loc[i:i,'Time'] 18    20091110_BjT0000
Name: Time, dtype: object

19
str11 [2009111012]
data.loc[i:i,'Time'] 19    20091110_BjT1200
Name: Time, dtype: object

20
str11 [2009111100]
data.loc[i:i,'Time'] 20    20091111_BjT0000
Name: Time, dtype: object

21
str11 [2009111112]
data.loc[i:i,'Time'] 21    20091111_BjT1200
Name: Time, dtype: object

22
str11 [2009111200]
data.loc[i:i,'Time'] 22    20091112_BjT0000
Name: Time, dtype: object

23
str11 [2009111212]
data.loc[i:i,'Time'] 23    20091112_BjT1200
Name: Time, dtype: object

24
str11 [2009111300]
data.loc[i:i,'Time'] 24    20091113_BjT0000
Name: Time, dtype: object

25
str11 [2009111312]
data.loc[i:i,'Time'] 25    20091113_BjT1200
Name: Time, dtype: object

26
str11 [2009111400]
data.loc[i:i,'Time'] 26    20091114_BjT0000
Name: Time, dtype: object

27
str11 [2009111412]
data.loc[i:i,'Time'] 27    20091114_BjT1200
Name: Time, dtype: object

28
str11 [2009111500]
data.loc[i:i,'Time'] 28    20091115_BjT0000
Name: Time, dtype: object

29
str11 [2009111512]
data.loc[i:i,'Time'] 29    20091115_BjT1200
Name: Time, dtype: object

30
str11 [2009111612]
data.loc[i:i,'Time'] 30    20091116_BjT1200
Name: Time, dtype: object

31
str11 [2009111700]
data.loc[i:i,'Time'] 31    20091117_BjT0000
Name: Time, dtype: object

32
str11 [2009111712]
data.loc[i:i,'Time'] 32    20091117_BjT1200
Name: Time, dtype: object

33
str11 [2009111800]
data.loc[i:i,'Time'] 33    20091118_BjT0000
Name: Time, dtype: object

34
str11 [2009111812]
data.loc[i:i,'Time'] 34    20091118_BjT1200
Name: Time, dtype: object

35
str11 [2009111900]
data.loc[i:i,'Time'] 35    20091119_BjT0000
Name: Time, dtype: object

36
str11 [2009111912]
data.loc[i:i,'Time'] 36    20091119_BjT1200
Name: Time, dtype: object

37
str11 [2009112000]
data.loc[i:i,'Time'] 37    20091120_BjT0000
Name: Time, dtype: object

38
str11 [2009112012]
data.loc[i:i,'Time'] 38    20091120_BjT1200
Name: Time, dtype: object

39
str11 [2009112100]
data.loc[i:i,'Time'] 39    20091121_BjT0000
Name: Time, dtype: object

40
str11 [2009112112]
data.loc[i:i,'Time'] 40    20091121_BjT1200
Name: Time, dtype: object

41
str11 [2009112200]
data.loc[i:i,'Time'] 41    20091122_BjT0000
Name: Time, dtype: object

42
str11 [2009112212]
data.loc[i:i,'Time'] 42    20091122_BjT1200
Name: Time, dtype: object

43
str11 [2009112300]
data.loc[i:i,'Time'] 43    20091123_BjT0000
Name: Time, dtype: object

44
str11 [2009112312]
data.loc[i:i,'Time'] 44    20091123_BjT1200
Name: Time, dtype: object

45
str11 [2009112400]
data.loc[i:i,'Time'] 45    20091124_BjT0000
Name: Time, dtype: object

46
str11 [2009112412]
data.loc[i:i,'Time'] 46    20091124_BjT1200
Name: Time, dtype: object

47
str11 [2009112500]
data.loc[i:i,'Time'] 47    20091125_BjT0000
Name: Time, dtype: object

48
str11 [2009112512]
data.loc[i:i,'Time'] 48    20091125_BjT1200
Name: Time, dtype: object

49
str11 [2009112600]
data.loc[i:i,'Time'] 49    20091126_BjT0000
Name: Time, dtype: object

50
str11 [2009112612]
data.loc[i:i,'Time'] 50    20091126_BjT1200
Name: Time, dtype: object

51
str11 [2009112700]
data.loc[i:i,'Time'] 51    20091127_BjT0000
Name: Time, dtype: object

52
str11 [2009112712]
data.loc[i:i,'Time'] 52    20091127_BjT1200
Name: Time, dtype: object

53
str11 [2009112800]
data.loc[i:i,'Time'] 53    20091128_BjT0000
Name: Time, dtype: object

54
str11 [2009112812]
data.loc[i:i,'Time'] 54    20091128_BjT1200
Name: Time, dtype: object

55
str11 [2009112900]
data.loc[i:i,'Time'] 55    20091129_BjT0000
Name: Time, dtype: object

56
str11 [2009112912]
data.loc[i:i,'Time'] 56    20091129_BjT1200
Name: Time, dtype: object

57
str11 [2009113000]
data.loc[i:i,'Time'] 57    20091130_BjT0000
Name: Time, dtype: object

58
str11 [2009113012]
data.loc[i:i,'Time'] 58    20091130_BjT1200
Name: Time, dtype: object

0
str11 [2009120100]
data.loc[i:i,'Time'] 0    20091201_BjT0000
Name: Time, dtype: object

1
str11 [2009120112]
data.loc[i:i,'Time'] 1    20091201_BjT1200
Name: Time, dtype: object

2
str11 [2009120200]
data.loc[i:i,'Time'] 2    20091202_BjT0000
Name: Time, dtype: object

3
str11 [2009120212]
data.loc[i:i,'Time'] 3    20091202_BjT1200
Name: Time, dtype: object

4
str11 [2009120300]
data.loc[i:i,'Time'] 4    20091203_BjT0000
Name: Time, dtype: object

5
str11 [2009120312]
data.loc[i:i,'Time'] 5    20091203_BjT1200
Name: Time, dtype: object

6
str11 [2009120400]
data.loc[i:i,'Time'] 6    20091204_BjT0000
Name: Time, dtype: object

7
str11 [2009120412]
data.loc[i:i,'Time'] 7    20091204_BjT1200
Name: Time, dtype: object

8
str11 [2009120500]
data.loc[i:i,'Time'] 8    20091205_BjT0000
Name: Time, dtype: object

9
str11 [2009120512]
data.loc[i:i,'Time'] 9    20091205_BjT1200
Name: Time, dtype: object

10
str11 [2009120600]
data.loc[i:i,'Time'] 10    20091206_BjT0000
Name: Time, dtype: object

11
str11 [2009120612]
data.loc[i:i,'Time'] 11    20091206_BjT1200
Name: Time, dtype: object

12
str11 [2009120700]
data.loc[i:i,'Time'] 12    20091207_BjT0000
Name: Time, dtype: object

13
str11 [2009120712]
data.loc[i:i,'Time'] 13    20091207_BjT1200
Name: Time, dtype: object

14
str11 [2009120800]
data.loc[i:i,'Time'] 14    20091208_BjT0000
Name: Time, dtype: object

15
str11 [2009120812]
data.loc[i:i,'Time'] 15    20091208_BjT1200
Name: Time, dtype: object

16
str11 [2009120900]
data.loc[i:i,'Time'] 16    20091209_BjT0000
Name: Time, dtype: object

17
str11 [2009120912]
data.loc[i:i,'Time'] 17    20091209_BjT1200
Name: Time, dtype: object

18
str11 [2009121000]
data.loc[i:i,'Time'] 18    20091210_BjT0000
Name: Time, dtype: object

19
str11 [2009121012]
data.loc[i:i,'Time'] 19    20091210_BjT1200
Name: Time, dtype: object

20
str11 [2009121100]
data.loc[i:i,'Time'] 20    20091211_BjT0000
Name: Time, dtype: object

21
str11 [2009121112]
data.loc[i:i,'Time'] 21    20091211_BjT1200
Name: Time, dtype: object

22
str11 [2009121200]
data.loc[i:i,'Time'] 22    20091212_BjT0000
Name: Time, dtype: object

23
str11 [2009121212]
data.loc[i:i,'Time'] 23    20091212_BjT1200
Name: Time, dtype: object

24
str11 [2009121300]
data.loc[i:i,'Time'] 24    20091213_BjT0000
Name: Time, dtype: object

25
str11 [2009121312]
data.loc[i:i,'Time'] 25    20091213_BjT1200
Name: Time, dtype: object

26
str11 [2009121400]
data.loc[i:i,'Time'] 26    20091214_BjT0000
Name: Time, dtype: object

27
str11 [2009121412]
data.loc[i:i,'Time'] 27    20091214_BjT1200
Name: Time, dtype: object

28
str11 [2009121500]
data.loc[i:i,'Time'] 28    20091215_BjT0000
Name: Time, dtype: object

29
str11 [2009121512]
data.loc[i:i,'Time'] 29    20091215_BjT1200
Name: Time, dtype: object

30
str11 [2009121600]
data.loc[i:i,'Time'] 30    20091216_BjT0000
Name: Time, dtype: object

31
str11 [2009121612]
data.loc[i:i,'Time'] 31    20091216_BjT1200
Name: Time, dtype: object

32
str11 [2009121700]
data.loc[i:i,'Time'] 32    20091217_BjT0000
Name: Time, dtype: object

33
str11 [2009121712]
data.loc[i:i,'Time'] 33    20091217_BjT1200
Name: Time, dtype: object

34
str11 [2009121800]
data.loc[i:i,'Time'] 34    20091218_BjT0000
Name: Time, dtype: object

35
str11 [2009121812]
data.loc[i:i,'Time'] 35    20091218_BjT1200
Name: Time, dtype: object

36
str11 [2009121900]
data.loc[i:i,'Time'] 36    20091219_BjT0000
Name: Time, dtype: object

37
str11 [2009121912]
data.loc[i:i,'Time'] 37    20091219_BjT1200
Name: Time, dtype: object

38
str11 [2009122000]
data.loc[i:i,'Time'] 38    20091220_BjT0000
Name: Time, dtype: object

39
str11 [2009122012]
data.loc[i:i,'Time'] 39    20091220_BjT1200
Name: Time, dtype: object

40
str11 [2009122100]
data.loc[i:i,'Time'] 40    20091221_BjT0000
Name: Time, dtype: object

41
str11 [2009122112]
data.loc[i:i,'Time'] 41    20091221_BjT1200
Name: Time, dtype: object

42
str11 [2009122200]
data.loc[i:i,'Time'] 42    20091222_BjT0000
Name: Time, dtype: object

43
str11 [2009122212]
data.loc[i:i,'Time'] 43    20091222_BjT1200
Name: Time, dtype: object

44
str11 [2009122300]
data.loc[i:i,'Time'] 44    20091223_BjT0000
Name: Time, dtype: object

45
str11 [2009122312]
data.loc[i:i,'Time'] 45    20091223_BjT1200
Name: Time, dtype: object

46
str11 [2009122400]
data.loc[i:i,'Time'] 46    20091224_BjT0000
Name: Time, dtype: object

47
str11 [2009122412]
data.loc[i:i,'Time'] 47    20091224_BjT1200
Name: Time, dtype: object

48
str11 [2009122500]
data.loc[i:i,'Time'] 48    20091225_BjT0000
Name: Time, dtype: object

49
str11 [2009122512]
data.loc[i:i,'Time'] 49    20091225_BjT1200
Name: Time, dtype: object

50
str11 [2009122600]
data.loc[i:i,'Time'] 50    20091226_BjT0000
Name: Time, dtype: object

51
str11 [2009122612]
data.loc[i:i,'Time'] 51    20091226_BjT1200
Name: Time, dtype: object

52
str11 [2009122700]
data.loc[i:i,'Time'] 52    20091227_BjT0000
Name: Time, dtype: object

53
str11 [2009122712]
data.loc[i:i,'Time'] 53    20091227_BjT1200
Name: Time, dtype: object

54
str11 [2009122812]
data.loc[i:i,'Time'] 54    20091228_BjT1200
Name: Time, dtype: object

55
str11 [2009122900]
data.loc[i:i,'Time'] 55    20091229_BjT0000
Name: Time, dtype: object

56
str11 [2009122912]
data.loc[i:i,'Time'] 56    20091229_BjT1200
Name: Time, dtype: object

57
str11 [2009123000]
data.loc[i:i,'Time'] 57    20091230_BjT0000
Name: Time, dtype: object

58
str11 [2009123012]
data.loc[i:i,'Time'] 58    20091230_BjT1200
Name: Time, dtype: object

59
str11 [2009123100]
data.loc[i:i,'Time'] 59    20091231_BjT0000
Name: Time, dtype: object